# Generated by Django 4.2.5 on 2023-10-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_client_owner_mailingsettings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Собственник'),
        ),
    ]
