# Generated by Django 4.2.5 on 2023-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=500, verbose_name='Содержимое')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('count_view', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колличество просмотров')),
                ('date_publication', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
